# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.18.4
# Mod Properties
mod_version=1.8.4
maven_group=com.v999
archives_base_name=sbutils
# Dependencies
# check this on https://fabricmc.net/develop
fabric_version=0.144.3+26.1
modmenu_version=18.0.0-alpha.6
